### ISSUE TITLE
how do I use this on bluestacks?

### ISSUE THREAD

**Issue by ShoelessTom** [httptoolkit/httptoolkit-android#25]
Connecting using adb bridge works for nox emulators, but it doesn't work for blue stacks 5 emulators. How do i Fix this? Thanks

**Comment by pimterry** [comment]
Is that because Bluestacks isn't connected to ADB at all, or something else? You can check by running `adb devices`. I think Bluestacks requires a few steps to get connected: https://stackoverflow.com/questions/54317727/how-do-you-adb-to-bluestacks-4.

Once it's connected everything should work correctly, but if not you can check the logs via Help -> View HTTP Toolkit Logs.
