### ISSUE TITLE
Use with apk installed certificate

### ISSUE THREAD

**Issue by Rufim** [httptoolkit/httptoolkit-android#29]
Currently if app cannot install certificate app reject to startup. But certificate already integrated in my app and i dont need to see all traffic.
Now only way is setup proxy on android to use with non rooted devices. 
Also please add compatibility with Android TV:  currently app not shows in app list(but works good with dpad still)

**Comment by pimterry** [comment]
Ah, that's interesting! I hadn't considered that use case. I think we could certainly 'skip certificate trust' as an option at that stage (but we probably do need to prompt every time you launch it without just pressing 'reconnect', but at least you would just have to press 'skip' to make it work). That would need a little bit of tweaking for the Connected UI too to show that state in a sensible way.

I don't know much about Android TV, I'm happy to add support for that but I'm not sure what's required.

Would you be interested in opening a PR for either of those changes? Just so you know, HTTP Toolkit Pro is totally free for all contributors.

**Comment by Rufim** [comment]
I created PR. You can use it as source to implement better way) 
https://github.com/httptoolkit/httptoolkit-android/pull/30

**Comment by pimterry** [comment]
This is now live at https://github.com/httptoolkit/httptoolkit-android/releases/tag/v1.5.0, and that version will be used for setup automatically by HTTP Toolkit on new devices.

Some delay in actually releasing this to the play store - turns out Android TV requires AAB, and some updated play store policy requires lots of other updates, but it's coming there too (which will prompt existing installs to update). Pending some review so that may take a week or two before it's live.

**Comment by pimterry** [comment]
Took ages, but this is now approved & live in the Play Store too :+1:
