### ISSUE TITLE
CA Location?

### ISSUE THREAD

**Issue by tortelloid** [httptoolkit/httptoolkit-android#3]
I prompted to manually install ca file, but i can't find it anywhere, where is the location in android device?

**Comment by tortelloid** [comment]
i found it in Downloads folder

**Comment by pimterry** [comment]
Glad you found it @tortelloid! It's placed there without instructions because on most devices/OSs that meant it automatically appears at the top of the file browser as a recent file.

Did that not happen in your case, or was that just not where you were looking? Could you let me know your device & OS so I can test?
